"""check_sync

Revision ID: 15670218bb0d
Revises: 3414408a4c10
Create Date: 2026-01-17 20:22:58.281378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15670218bb0d'
down_revision: Union[str, None] = '3414408a4c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gitlab_project_members_role_id_fkey', 'gitlab_project_members', type_='foreignkey')
    op.drop_table('sys_role_permissions')
    op.drop_table('rbac_permissions')
    op.drop_table('rbac_roles')
    op.create_foreign_key(None, 'gitlab_project_members', 'sys_role', ['role_id'], ['id'])
    op.alter_column('sys_menu', 'parent_id',
               existing_type=sa.INTEGER(),
               comment='父菜单ID (0或NULL表示顶级)',
               existing_comment='父菜单ID',
               existing_nullable=True)
    op.create_foreign_key(None, 'sys_menu', 'sys_menu', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sys_menu', type_='foreignkey')
    op.alter_column('sys_menu', 'parent_id',
               existing_type=sa.INTEGER(),
               comment='父菜单ID',
               existing_comment='父菜单ID (0或NULL表示顶级)',
               existing_nullable=True)
    op.drop_constraint(None, 'gitlab_project_members', type_='foreignkey')
    op.create_foreign_key('gitlab_project_members_role_id_fkey', 'gitlab_project_members', 'rbac_roles', ['role_id'], ['id'])
    op.create_table('rbac_roles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('rbac_roles_id_seq'::regclass)"), autoincrement=True, nullable=False, comment='角色ID'),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='角色代码 (admin/pm/dev/viewer)'),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='角色显示名称'),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='角色描述'),
    sa.PrimaryKeyConstraint('id', name='rbac_roles_pkey'),
    sa.UniqueConstraint('code', name='rbac_roles_code_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('name', name='rbac_roles_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('sys_role_permissions',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='角色ID'),
    sa.Column('permission_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='权限代码'),
    sa.ForeignKeyConstraint(['permission_code'], ['rbac_permissions.code'], name='sys_role_permissions_permission_code_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_roles.id'], name='sys_role_permissions_role_id_fkey'),
    sa.PrimaryKeyConstraint('role_id', 'permission_code', name='sys_role_permissions_pkey')
    )
    op.create_table('rbac_permissions',
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='权限代码 (如 ticket:create)'),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='权限分类 (ticket/project/admin)'),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='权限描述'),
    sa.PrimaryKeyConstraint('code', name='rbac_permissions_pkey')
    )
    # ### end Alembic commands ###
