"""add_cognitive_complexity_column

Revision ID: 2a026ee8eec0
Revises:
Create Date: 2026-01-10 14:10:36.065518

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "2a026ee8eec0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查表是否存在后再删除，防止在从空库初始化时报错
    bind = op.get_bind()
    from sqlalchemy import inspect

    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    if "hr_employees" in existing_tables:
        op.drop_table("hr_employees")
    if "ldap_accounts" in existing_tables:
        op.drop_table("ldap_accounts")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ldap_accounts",
        sa.Column("employee_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("email", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("sam_account_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_logon_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "hr_employees",
        sa.Column("employee_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("full_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("department_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("job_title", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("status", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
