"""add_cognitive_complexity_column

Revision ID: 2a026ee8eec0
Revises: 
Create Date: 2026-01-10 14:10:36.065518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a026ee8eec0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hr_employees')
    op.drop_table('ldap_accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ldap_accounts',
    sa.Column('employee_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sam_account_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_logon_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('hr_employees',
    sa.Column('employee_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('department_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
