"""extend_sync_log_with_external_fields

Revision ID: b1cf984c9cd9
Revises: 24a4cf7d18f5
Create Date: 2026-03-17 06:51:57.749958

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b1cf984c9cd9"
down_revision: str | None = "24a4cf7d18f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sys_sync_logs", sa.Column("external_id", sa.String(length=100), nullable=True, comment="来源系统原始ID"))
    op.add_column("sys_sync_logs", sa.Column("source", sa.String(length=50), nullable=True, comment="来源系统类型 (gitlab/zentao/sonarqube)"))
    op.create_index(op.f("ix_sys_sync_logs_external_id"), "sys_sync_logs", ["external_id"], unique=False)
    op.create_index(op.f("ix_sys_sync_logs_source"), "sys_sync_logs", ["source"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sys_sync_logs_source"), table_name="sys_sync_logs")
    op.drop_index(op.f("ix_sys_sync_logs_external_id"), table_name="sys_sync_logs")
    op.drop_column("sys_sync_logs", "source")
    op.drop_column("sys_sync_logs", "external_id")
    # ### end Alembic commands ###
