
devops_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'db') }}"
      user: "{{ env_var('POSTGRES_USER', 'postgres') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD', 'devops123') }}"
      port: "{{ env_var('DB_PORT', 5432) | as_number }}"
      dbname: "{{ env_var('POSTGRES_DB', 'devops_db') }}"
      schema: public
      threads: 4
