version: 2

sources:
  - name: raw
    description: "多源原始数据 landing 层"
    tables:
      # 1. HR 系统原始表 (信任级别：高 - 属性：姓名、组织)
      - name: hr_employees
        description: "HR 系统员工全量表"
      
      # 2. LDAP 系统原始表 (信任级别：高 - 属性：邮箱、账号)
      - name: ldap_accounts
        description: "LDAP 目录服务账号表"

      # 3. MDM Identities (作为主键映射表)
      - name: mdm_identities
        description: "主数据 ID 索引表"
